#!/bin/sh
# Generate docs/commands.md from the executable files in tools/.
#
#   sh devtools/command-surface.sh > docs/commands.md
#
# SOURCE_ROOT may point at a clean source snapshot when the working tree has
# unrelated edits. The default is the repository containing this script.
set -eu

script_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
source_root=${SOURCE_ROOT:-$script_root}
tools_dir="$source_root/tools"

VERB='GET|POST|PUT|PATCH|DELETE'

methods_of() {
  {
    grep -Eo '(/tools/call"|\$CALL_BIN") +('"$VERB"')' "$1" || true
    grep -Eo -- '-X +('"$VERB"')' "$1" || true
    grep -Eo 'METHOD=('"$VERB"')' "$1" || true
    grep -q 'invalid --method' "$1" && printf 'PUT\n' || true
    grep -Eq 'paginate_json|paginate_tabular' "$1" && printf 'GET\n' || true
    grep -q 'RESPONSE=\$(curl' "$1" && printf 'GET\n' || true
  } 2>/dev/null | grep -Eo "($VERB)\$" | sort -u | paste -sd, - || true
}

path_of() {
  file=$1
  path=''
  for expr in \
    's/.*${PATH_OVERRIDE:-\([^}]*\)}.*/\1/p' \
    's/^def_path="\([^"]*\)".*/\1/p' \
    's/^PATH_INC="\([^"]*\)".*/\1/p' \
    's/^TEST_ENDPOINT="\([^"]*\)".*/\1/p'
  do
    path=$(sed -n "$expr" "$file" | grep '^/' | head -1) || true
    [ -n "$path" ] && break
  done
  if [ -z "$path" ]; then
    path=$(grep -Eo '(/tools/call"|\$CALL_BIN") +("\$METHOD"|'"$VERB"') +"[^"]*"' "$file" \
      | grep -Eo '"[^"]*"$' | tr -d '"' | grep '^/' | head -1) || true
  fi
  printf '%s' "${path:-}" \
    | sed 's/\$ID/{id}/g; s/\$AID/{attachmentId}/g; s/\$NUM/{number}/g'
}

options_of() {
  sed -n 's/^ *\(-[^)]*\)).*/\1/p' "$1" \
    | tr '|' '\n' \
    | sed 's/^ *//; s/ *$//; s/=$//' \
    | grep -E '^--?[A-Za-z]' \
    | sort -u \
    | wc -l \
    | tr -d ' '
}

printf '%s\n\n' '# Command surface'
printf '%s\n\n' '[← back to the overview](../README.md)'
printf '%s\n\n' 'Generated by `sh devtools/command-surface.sh`; one row per executable in `tools/`.'
printf '| Command | Method | Default path | Options | Lines |\n'
printf '|---|---|---|--:|--:|\n'

find "$tools_dir" -mindepth 1 -maxdepth 1 -type f -perm +111 2>/dev/null \
  | LC_ALL=C sort \
  | while IFS= read -r file; do
      name=$(basename "$file")
      method=$(methods_of "$file")
      [ -n "$method" ] || method='—'
      path=$(path_of "$file")
      if [ -n "$path" ]; then path="\`$path\`"; else path='—'; fi
      options=$(options_of "$file")
      lines=$(wc -l < "$file" | tr -d ' ')
      printf '| `%s` | %s | %s | %s | %s |\n' \
        "$name" "$method" "$path" "$options" "$lines"
    done
